# baseurl = "https://username.github.io"
baseurl = "https://MAP-VERSE.github.io/Repository/"
DefaultContentLanguage = "en"
title = "MAP-VERSE"
# Using theme as git submodule 
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[taxonomies]
  tag = "tags"
# series = "series"

[Params]
  homeTitle = "MAP-VERSE"
  subtitle = "MAP usability - Validated Empirical Research by Systematic Evaluation"
  mainSections = ["post","posts"]
  logo = "img/mv.png" # Expecting square dimensions
  favicon = "img/mv.ico"
  dateFormat = "January 2, 2006"

  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  customCSS = ["css/custom.css"]
  since = "2024"
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
  gcse = "6594bf4f7a48445fa" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

[[Params.bigimg]]
  src = "img/bg3.jpg"
#  desc = "MAP-VERSE"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Cartographers & GISers"
#  website = "yourwebsite.com"
#  email = "youremail@domain.com"
#  facebook = "username"
  github = "https://github.com/MAP-VERSE/Repository"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
#  mastodon = "url"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"
#  medium = "username"
#  discord = "invite code (https://discord.gg/XXXXXXX)"
#  strava = "userid"

[[menu.main]]
    name = "Homepage"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

#[[menu.main]]
#    identifier = "samples"
#    name = "Samples"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1

#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "post/2016-03-08-code-sample"
#    weight = 3

[[menu.main]]
    name = "Keywords"
    url = "tags"
    weight = 3

#[[menu.main]]
#    name = "Sample Size"
#    url = "series"
#    weight = 3

[[menu.main]]
    name = "Tools"
    identifier = "experimental-tools"
    url = "post/data_tools"
    weight = 4

[[menu.main]]
    name = "License"
    url = "page/license_mit"
    weight = 5